# Site settings
title:
email: bsdpunk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A perfect philosophy executed by an imperfect being. A blog by a failure, who thought he was a hacker. Musings, fiction, and system adminstration.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "bsdpunk.github.com" # the base hostname & protocol for your site
twitter_username: bsdpunk
github_username: bsdpunk

# Build settings
markdown: kramdown
